# Generated by Django 6.0.4 on 2026-04-28 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('swimming_level', models.CharField(choices=[('beginner', 'Новичок'), ('amateur', 'Любитель'), ('advanced', 'Продвинутый'), ('pro', 'Профессионал')], default='beginner', max_length=20, verbose_name='Уровень')),
                ('medical_notes', models.TextField(blank=True, verbose_name='Мед. противопоказания')),
                ('parent_contact', models.CharField(blank=True, max_length=20, verbose_name='Контакт родителя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмены',
            },
        ),
        migrations.CreateModel(
            name='FanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_athletes', models.ManyToManyField(blank=True, to='users.athleteprofile', verbose_name='Любимые спортсмены')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fan_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Болельщик',
                'verbose_name_plural': 'Болельщики',
            },
        ),
    ]
