# Generated by Django 5.1.15 on 2026-04-29 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_athleteprofile_fanprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('achievement_type', models.CharField(choices=[('record', 'Рекорд школы'), ('medal', 'Медаль'), ('rank', 'Разряд'), ('other', 'Другое')], max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('competition', models.CharField(blank=True, max_length=200, verbose_name='Соревнование')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.athleteprofile', verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-date'],
            },
        ),
    ]
