# Generated by Django 5.0 on 2026-05-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_athleteprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
    ]
