# Generated by Django 5.0 on 2026-05-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_athleteprofile_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж плавания (лет)'),
        ),
    ]
