# Generated by Django 5.0 on 2026-05-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='certifications',
            field=models.TextField(blank=True, verbose_name='Сертификаты и лицензии'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='programs',
            field=models.TextField(blank=True, verbose_name='Программы и услуги'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='schedule',
            field=models.TextField(blank=True, verbose_name='График работы / расписание'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='whatsapp_url',
            field=models.URLField(blank=True, verbose_name='WhatsApp'),
        ),
    ]
