# Generated by Django 5.0 on 2026-05-05 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_heatassignment_status'),
        ('news', '0002_newscomment_newslike'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='competitions.competition', verbose_name='Соревнование'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/', verbose_name='Изображение'),
        ),
    ]
