# Generated by Django 6.0.4 on 2026-04-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('map_link', models.URLField(blank=True, verbose_name='Ссылка на карту')),
                ('photo', models.ImageField(upload_to='branches/', verbose_name='Фото')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('schedule', models.TextField(verbose_name='Расписание работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
    ]
