# Generated by Django 5.1.15 on 2026-05-09 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0003_competition_registration_deadline_time'),
        ('users', '0005_athleteprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_time', models.CharField(max_length=20, verbose_name='Результат')),
                ('result_seconds', models.FloatField(default=0, verbose_name='Результат (сек)')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='users.athleteprofile', verbose_name='Спортсмен')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.competition', verbose_name='Соревнование')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='competitions.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Личный рекорд',
                'verbose_name_plural': 'Личные рекорды',
                'ordering': ['discipline', 'result_seconds'],
            },
        ),
        migrations.CreateModel(
            name='AthleteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_time', models.CharField(max_length=20, verbose_name='Результат')),
                ('result_seconds', models.FloatField(verbose_name='Результат (сек)')),
                ('place', models.PositiveIntegerField(blank=True, null=True, verbose_name='Место')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.athleteprofile', verbose_name='Спортсмен')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition', verbose_name='Соревнование')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_results', to='competitions.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Результат спортсмена',
                'verbose_name_plural': 'Результаты спортсменов',
                'ordering': ['date'],
                'unique_together': {('athlete', 'discipline', 'competition')},
            },
        ),
    ]
