# Generated by Django 5.1.15 on 2026-04-29 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('users', '0003_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('location', models.CharField(max_length=300, verbose_name='Место проведения')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('registration_deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн регистрации')),
                ('program', models.TextField(blank=True, verbose_name='Программа соревнований')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящее'), ('ongoing', 'Идёт сейчас'), ('finished', 'Завершено'), ('cancelled', 'Отменено')], default='upcoming', max_length=10, verbose_name='Статус')),
                ('max_participants', models.PositiveIntegerField(default=0, verbose_name='Максимум участников')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('image', models.ImageField(blank=True, upload_to='competitions/', verbose_name='Баннер')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='branches.branch', verbose_name='Филиал-организатор')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=200, verbose_name='Дисциплина')),
                ('place', models.PositiveIntegerField(blank=True, null=True, verbose_name='Место')),
                ('result_time', models.CharField(blank=True, max_length=50, verbose_name='Результат')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.athleteprofile', verbose_name='Спортсмен')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.competition', verbose_name='Соревнование')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ['discipline', 'place'],
            },
        ),
        migrations.CreateModel(
            name='BranchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('gold', models.PositiveIntegerField(default=0, verbose_name='Золото')),
                ('silver', models.PositiveIntegerField(default=0, verbose_name='Серебро')),
                ('bronze', models.PositiveIntegerField(default=0, verbose_name='Бронза')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Филиал')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_scores', to='competitions.competition', verbose_name='Соревнование')),
            ],
            options={
                'verbose_name': 'Зачёт филиала',
                'verbose_name_plural': 'Зачёт филиалов',
                'unique_together': {('competition', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.athleteprofile', verbose_name='Спортсмен')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.competition', verbose_name='Соревнование')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'unique_together': {('competition', 'athlete')},
            },
        ),
    ]
