# Generated by Django 5.0 on 2026-05-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competition_registration_deadline_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatassignment',
            name='status',
            field=models.CharField(blank=True, choices=[('finished', 'Завершен'), ('dnf', 'Не финишировал'), ('disqualified', 'Дисквалифицирован'), ('false_start', 'Фальстарт')], max_length=20, verbose_name='Статус финиша'),
        ),
    ]
